name: Flying Blue XP Bot

on:
  schedule:
    - cron: "0 * * * *"   # draait elk uur
  workflow_dispatch:       # je kunt het ook handmatig starten

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
        run: python bot.py

      - name: Commit updated feed
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add feed.xml deals.csv
          git commit -m "Update feed from bot" || echo "No changes to commit"
          git push
