name: Flying Blue XP Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"  # draait elk uur

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run leg-finder
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
        run: python3 bot_legfinder.py

      - name: Rebuild feed.xml
        run: python3 generate_feed.py

      - name: Commit & push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add deals.csv feed.xml || true
          git commit -m "Auto-update via legfinder" || echo "No changes to commit"
          git pull --rebase
          git push
